bool blocks[7][4][4][4] =
    {
        ///////
        {
            {{false, false, false, false},
             {false, false, false, false},
             {true, true, true, true},
             {false, false, false, false}},
            {{false, false, true, false},
             {false, false, true, false},
             {false, false, true, false},
             {false, false, true, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {true, true, true, true},
             {false, false, false, false}},
            {{false, false, true, false},
             {false, false, true, false},
             {false, false, true, false},
             {false, false, true, false}}},
        ///////
        {
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, false},
             {false, false, true, true}},
            {{false, false, false, false},
             {false, false, true, false},
             {false, true, true, false},
             {false, true, false, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, false},
             {false, false, true, true}},
            {{false, false, false, false},
             {false, false, true, false},
             {false, true, true, false},
             {false, true, false, false}}},
        ///////
        {
            {{false, false, false, false},
             {false, false, false, false},
             {false, false, true, true},
             {false, true, true, false}},
            {{false, false, false, false},
             {false, true, false, false},
             {false, true, true, false},
             {false, false, true, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, false, true, true},
             {false, true, true, false}

            },
            {{false, false, false, false},
             {false, true, false, false},
             {false, true, true, false},
             {false, false, true, false}}},
        ///////
        {
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, false, false},
             {false, true, true, true}},
            {{false, false, false, false},
             {false, true, true, false},
             {false, true, false, false},
             {false, true, false, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, true},
             {false, false, false, true}},
            {{false, false, false, false},
             {false, false, true, false},
             {false, false, true, false},
             {false, true, true, false}}},
        ///////
        {
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, true},
             {false, true, false, false}},
            {{false, false, false, false},
             {false, true, true, false},
             {false, false, true, false},
             {false, false, true, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, false, false, true},
             {false, true, true, true}},
            {{false, false, false, false},
             {false, true, false, false},
             {false, true, false, false},
             {false, true, true, false}}},
        ///////
        {
            {{false, false, false, false},
             {false, false, false, false},
             {false, false, true, false},
             {false, true, true, true}},
            {{false, false, false, false},
             {false, true, false, false},
             {false, true, true, false},
             {false, true, false, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, true},
             {false, false, true, false}},
            {{false, false, false, false},
             {false, false, true, false},
             {false, true, true, false},
             {false, false, true, false}}},
        ///////
        {
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, false},
             {false, true, true, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, false},
             {false, true, true, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, false},
             {false, true, true, false}},
            {{false, false, false, false},
             {false, false, false, false},
             {false, true, true, false},
             {false, true, true, false}}}};
